# This is a placeholder so actions won't default to a getting started page

name: Placeholder

#on: push
#on:
  #push: 
    #branches: [main]

on:
  workflow_call:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world nitin
