# This is a placeholder so actions won't default to a getting started page

name: Placeholder

#on: push
on:
  push: 
    branches: [main]
    

#on:
  #workflow_call:
  

#on:
    #issue_comment:
      #types: [created]
      
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref }} 
  packer_working_dir: function
  
  
  
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      
      - name: check the variables
        id: checkrepo
        env:
            repo: ${{github.repository}}
            repo_owner: ${{github.repository_owner}}
        run: |
          repo=$repo;
          repoowner=$repo_owner;
          repostring=${repo#repoowner};
          echo "$repostring"
          echo ${{steps.checkrepo.outputs}}
          echo ::set-output name=outvalue::$( echo $repostring )
          
           
      - name: print checkrepo value     
        run: echo ${{steps.checkrepo.outputs.outvalue}}      

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ env.BRANCH_NAME }}
      
      - name: Run a one-line script
        run: |
          echo Hello, world nitin
          ls ${{steps.checkrepo.outputs.outvalue}} 

      - name: nstring
        id: ns
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.repository }}

      - name: print string name 
        run: |
          echo ${{ steps.ns.outputs.capitalized }}
          echo ${{ github.sha }}     
          echo sec ${{ env.BRANCH_NAME }}-shukla
          
      - name: Check the commands
        run: |
          echo $PATH
          which session-manager-plugin
          session-manager-plugin --version
          aws --version     

      - name: Validate Templates
        working-directory: ${{ env.packer_working_dir }}
        run: ls
        #run: packer validate -syntax-only ${{ env.packer_file_name }}
